Repository infosupport/tech-survey, pull requests merged in 2025-03, with the labels that each got.

#173 Bugfix: Only allow users to make requests for themselves
  src/server/api/routers/survey.ts
Labels: bug

#179 Reproducible dev environment - #178
  .env.example
  .envrc
  .gitignore
  README.md
  flake.lock
  flake.nix
  package-lock.json
  package.json
Labels: enhancement

#170 Bugfix: Move fetching of user information to client side
  src/app/page.tsx
  src/components/loading/communication-preferences-selection-loader.tsx
  src/components/loading/role-selection-loader.tsx
  src/components/select-businessunit.tsx
  src/components/select-communication-method.tsx
  src/components/select-input.tsx
  src/server/api/routers/survey.ts
  tests/survey-page.ts
Labels: bug

#184 `fix(layout)` | Fix uneven layout on the `Find the Expert` page
  src/components/ui/show-tech-search-wrapper.tsx
Labels: bug

#186 `fix(home-button)` | Fix home-button visibility and use hybrid rendering
  .vscode/settings.json
  src/app/layout.tsx
  src/components/home-link/home-link_client.tsx
  src/components/home-link/home-link_server.tsx
  src/components/home-link/index.tsx
  src/middleware.ts
Labels: bug, waiting

#187 `fix(dev-slow)` | Use Turbopack for development
  package.json
  src/app/layout.tsx
  src/components/home-link.tsx
  src/components/home-link/home-link_client.tsx
  src/components/home-link/home-link_server.tsx
  src/components/home-link/index.tsx
  src/middleware.ts
Labels: bug

#202 fix(profile-page): fix `getTicksOfAxis is null` error
  src/app/find-the-expert/profile-page/page.tsx
Labels: bugfix

#203 fix(profile-page): Fix errors & UI on profile page without survey results
  src/app/find-the-expert/profile-page/page.tsx
  src/components/profile-radar-chart.tsx
Labels: bugfix

#205 fix(profile-radar-chart): make radar-chart responsive
  src/app/find-the-expert/profile-page/page.tsx
  src/components/profile-radar-chart.tsx
  src/styles/globals.css
Labels: bugfix

#211 test(all): refactor tests & add first test for find-the-expert page
  next.config.js
  playwright.config.ts
  src/app/[...not_found]/page.tsx
  src/app/result/page.tsx
  tests/db-helper.ts
  tests/find-the-expert-page.ts
  tests/find-the-expert-tests.spec.ts
  tests/helpers/db/index.ts
  tests/helpers/db/survey.ts
  tests/helpers/db/user.ts
  tests/helpers/test-setup.ts
  tests/survey-page.ts
  tests/test-setup.ts
  tests/test.spec.ts
Labels: feature

#215 test(all): improve & greatly speed up tests
  .github/workflows/playwright.yml
  package.json
  playwright.config.ts
  src/auth.ts
  tests/helpers/db/index.ts
  tests/helpers/test-setup.ts
Labels: feature, bugfix

#218 docs(local-development): improve installation instructions
  README.md
Labels: documentation

#217 Only show results for currently selected roles on profile page
  next.config.ts
  src/app/find-the-expert/profile-page/page.tsx
  src/components/ui/search-anonymized.tsx
  src/server/db/prisma-client/answer-option.ts
  src/server/db/prisma-client/business-unit.ts
  src/server/db/prisma-client/question-result.ts
  src/server/db/prisma-client/role.ts
  src/server/db/prisma-client/survey.ts
  src/server/db/prisma-client/user.ts
  tsconfig.json
Labels: bugfix

#219 chore(lint): treat lint warnings as errors so they fail CI
  package.json
Labels: feature

#221 refactor(prisma): use PostgreSQL naming conventions
  .env.example
  flake.nix
  prisma/migrations/20250313143236_use_postgresql_naming_conventions/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  src/app/find-the-expert/profile-page/page.tsx
  src/app/result/page.tsx
  src/components/download-pdf.tsx
  src/components/loading/survey-question-loader.tsx
  src/components/mobile/survey-questions.tsx
  src/components/select-roles.tsx
  src/components/survey-questions.tsx
  src/models/types.ts
  src/server/db/prisma-client/question-result.ts
  src/server/db/prisma-client/survey.ts
  src/server/db/prisma-client/usage-metric.ts
  src/server/db/prisma-client/user.ts
  src/utils/data-manipulation.ts
  tests/helpers/db/survey.ts
Labels: feature

#225 fix(middleware): update NextJS to 15.2.3 to fix vulnerable middleware
  package-lock.json
  package.json
  prisma/seed-database-dummy-data.ts
  src/trpc/react.tsx
Labels: bugfix
